const CLASS_FEATURE_DESCRIPTIONS = [
  {name_ko:"오컬트 주문시전", name_en:"Occult Spellcasting", cat:"feature", class_id:"bard", feat_level:1, summary:"비밀스러운 지식에서 마법을 끌어옵니다. 오컬트(occult) 전통의 주문시전자로, 주문 시전(Cast a Spell) 활동을 사용합니다(299페이지). 바드로서 주문을 시전할 때, 주문은 음악적 리프나 영리한 리메릭일 수 있고, 몸짓은 춤과 극적인 판토마임을 포함할 수 있으며, 악기를 연주하며 주문시전을 동반할 수 있습니다. 매일 최대 2개의 1랭크 주문을 시전할 수 있습니다. 주문을 시전하려면 알고 있어야 하며, 주문 레퍼토리 클래스 특성을 통해 배웁니다. 매일 시전할 수 있는 주문 수를 주문 슬롯이라 합니다. 일부 주문은 주문 공격을 시도하거나 적이 주문 DC에 대해 내성 굴림을 해야 합니다. 핵심 속성이 매력이므로, 주문 공격 수정치와 주문 DC는 매력 수정치를 사용합니다."},
  {name_ko:"작곡 주문", name_en:"Composition Spells", cat:"feature", class_id:"bard", feat_level:1, summary:"공연에 마법을 불어넣어 작곡(composition)라는 고유한 효과를 만들 수 있습니다. 작곡는 공연(Performance) 기술을 사용해야 하는 경우가 많은 특수 유형의 주문입니다. 작곡 주문은 집중 주문(focus spell)의 일종입니다. 집중 주문 1개를 시전하는 데 집중 포인트 1점이 필요하며, 집중 풀 1점으로 시작합니다. 일일 준비 시 집중 풀을 채우고, 10분간 공연하거나 새 작곡를 작곡하거나 뮤즈에 몰입하는 재집중(Refocus) 활동으로 1점을 회복할 수 있습니다. 반격 공연(counter performance) 작곡(370페이지)를 배워, 청각과 시각 효과에 대항하여 보호합니다."},
  {name_ko:"번개 반사", name_en:"Lightning Reflexes", cat:"feature", class_id:"bard", feat_level:3, summary:"위험을 피하는 재주가 생겼습니다. 반사 내성 숙련도가 전문가로 증가."},
  {name_ko:"시그니처 주문", name_en:"Signature Spells", cat:"feature", class_id:"bard", feat_level:3, summary:"경험으로 일부 주문을 더 유연하게 시전할 수 있습니다. 접근 가능한 각 주문 랭크마다 시그니처 주문 1개를 선택합니다. 시그니처 주문의 고양 버전은 별도로 배울 필요 없이 자유롭게 고양할 수 있습니다. 최소 랭크보다 높은 랭크에서 시그니처 주문을 배웠다면, 별도로 배우지 않고도 모든 낮은 랭크 버전도 시전할 수 있습니다."},
  {name_ko:"전문가 주문시전자", name_en:"Expert Spellcaster", cat:"feature", class_id:"bard", feat_level:7, summary:"마법 기법이 강해집니다. 주문 공격 수정치와 주문 DC 숙련도가 전문가로 증가."},
  {name_ko:"큰 결의", name_en:"Resolve", cat:"feature", class_id:"bard", feat_level:9, summary:"최고의 공연은 자신의 마음에 대한 이해와 완벽한 집중을 요합니다. 의지 내성 숙련도가 대가로 증가. 의지 내성에서 성공을 굴리면 대성공."},
  {name_ko:"경각 감각", name_en:"Vigilant Senses", cat:"feature", class_id:"bard", feat_level:11, summary:"예리한 인식력과 세부 사항에 대한 주의력을 발달시켰습니다. 감지 숙련도가 대가로 증가."},
  {name_ko:"무기 전문화", name_en:"Weapon Specialization", cat:"feature", class_id:"bard", feat_level:11, summary:"가장 잘 아는 무기로 더 큰 부상을 입힐 수 있습니다. 전문가인 무기와 비무장 공격으로 추가 피해 2. 대가이면 3, 전설이면 4."},
  {name_ko:"경갑 전문화", name_en:"Light Armor Expertise", cat:"feature", class_id:"bard", feat_level:13, summary:"경갑이나 비무장 상태에서 피하는 법을 배웠습니다. 경갑과 비무장 방어 숙련도가 전문가로 증가."},
  {name_ko:"대가 주문시전자", name_en:"Master Spellcaster", cat:"feature", class_id:"bard", feat_level:15, summary:"하프의 줄처럼 마법의 실을 뜯습니다. 주문 공격 수정치와 주문 DC 숙련도가 대가로 증가."},
  {name_ko:"전설 주문시전자", name_en:"Legendary Spellcaster", cat:"feature", class_id:"bard", feat_level:19, summary:"공연이 우주의 기초를 뒤흔들 수 있습니다. 주문 공격 수정치와 주문 DC 숙련도가 전설로 증가."},
  {name_ko:"마기스터리 주문", name_en:"Magistry Spells", cat:"feature", class_id:"bard", feat_level:19, summary:"가장 강력한 주문시전을 완성했습니다. 오컬트 목록에서 10랭크 주문 1개를 레퍼토리에 추가합니다. 10랭크 주문 슬롯 1개를 얻으며, 이 슬롯으로만 이 주문을 시전할 수 있습니다. 다른 주문 슬롯과 달리, 레벨을 올려도 새 10랭크 슬롯을 얻지 못하지만, 주문을 재훈련으로 교환할 수 있습니다."},
  {name_ko:"신성 주문시전", name_en:"Divine Spellcasting", cat:"feature", class_id:"cleric", feat_level:1, summary:"신격의 힘과 신앙으로 신성(divine) 전통의 주문을 시전합니다. 매일 아침 기도와 명상으로 준비하여, 신성 주문 목록에서 시전할 주문을 선택해 주문 슬롯에 \"로드\"합니다. 핵심 속성이 지혜이므로 주문 DC와 공격 수정치에 지혜를 사용합니다."},
  {name_ko:"신성 글꼴", name_en:"Divine Font", cat:"feature", class_id:"cleric", feat_level:1, summary:"신격이 특별히 강화된 에너지에 접근을 부여합니다. 치유(heal) 또는 해로움(harm)에 대해 추가 주문 슬롯을 얻으며, 슬롯 수는 1 + 매력 수정치입니다. 글꼴이 둘 다 허용하면 매일 하나를 선택합니다."},
  {name_ko:"2차 교의", name_en:"Second Doctrine", cat:"feature", class_id:"cleric", feat_level:3, summary:"선택한 교의의 2차 혜택을 얻습니다(3레벨)."},
  {name_ko:"감지 전문가", name_en:"Alertness", cat:"feature", class_id:"cleric", feat_level:5, summary:"감지 숙련도가 전문가로 증가."},
  {name_ko:"3차 교의", name_en:"Third Doctrine", cat:"feature", class_id:"cleric", feat_level:7, summary:"선택한 교의의 3차 혜택을 얻습니다(7레벨)."},
  {name_ko:"확고한 신앙", name_en:"Steadfast Faith", cat:"feature", class_id:"cleric", feat_level:9, summary:"의지 내성에서 대실패 시 실패가 됩니다."},
  {name_ko:"4차 교의", name_en:"Fourth Doctrine", cat:"feature", class_id:"cleric", feat_level:11, summary:"선택한 교의의 4차 혜택을 얻습니다(11레벨)."},
  {name_ko:"신성 방어", name_en:"Divine Defense", cat:"feature", class_id:"cleric", feat_level:13, summary:"비무장 방어가 전문가로 증가."},
  {name_ko:"무기 전문화", name_en:"Weapon Specialization", cat:"feature", class_id:"cleric", feat_level:13, summary:"전문가인 무기와 비무장 공격으로 추가 피해 2(대가 3, 전설 4)."},
  {name_ko:"5차 교의", name_en:"Fifth Doctrine", cat:"feature", class_id:"cleric", feat_level:15, summary:"선택한 교의의 5차 혜택을 얻습니다(15레벨)."},
  {name_ko:"6차 교의", name_en:"Sixth Doctrine", cat:"feature", class_id:"cleric", feat_level:17, summary:"선택한 교의의 6차 혜택을 얻습니다(17레벨)."},
  {name_ko:"최종 교의", name_en:"Final Doctrine", cat:"feature", class_id:"cleric", feat_level:19, summary:"선택한 교의의 최종 혜택을 얻습니다(19레벨)."},
  {name_ko:"기적의 주문", name_en:"Miraculous Spells", cat:"feature", class_id:"cleric", feat_level:19, summary:"신성 주문 목록에서 10랭크 주문 1개 + 10랭크 슬롯 1개."},
  {name_ko:"원시 주문시전", name_en:"Primal Spellcasting", cat:"feature", class_id:"druid", feat_level:1, summary:"야생 세계의 힘이 당신을 통해 흐릅니다. 근원(primal) 전통의 주문시전자입니다. 매일 아침 근원 주문 목록에서 주문을 준비합니다."},
  {name_ko:"드루이드 결사", name_en:"Druidic Order", cat:"feature", class_id:"druid", feat_level:1, summary:"드루이드가 되면 결사와 자신을 맞추며, 클래스 재주, 결사 주문, 추가 숙련 기술을 얻습니다."},
  {name_ko:"방패 막기", name_en:"Shield Block", cat:"feature", class_id:"druid", feat_level:1, summary:"방패 막기(Shield Block) 일반 재주(262페이지)를 얻습니다."},
  {name_ko:"자연의 목소리", name_en:"Voice of Nature", cat:"feature", class_id:"druid", feat_level:1, summary:"동물 공감(Animal Empathy) 또는 식물 공감(Plant Empathy) 드루이드 재주 중 하나를 선택하여 얻습니다."},
  {name_ko:"야생노래", name_en:"Wildsong", cat:"feature", class_id:"druid", feat_level:1, summary:"드루이드 결사 내에서만 알려진 비밀 언어인 야생노래를 알고 있습니다. 이것은 동물 울음소리에 가까운 선율적이고 음조적인 언어이며, 그 알파벳은 조개껍데기의 방, 눈송이의 결정, 고사리의 잎처럼 프랙탈과 나선으로 이루어져 있습니다. 비드루이드에게 야생노래를 가르치는 것은 금기입니다."},
  {name_ko:"감지 전문가", name_en:"Alertness", cat:"feature", class_id:"druid", feat_level:3, summary:"감지 숙련도가 전문가로 증가."},
  {name_ko:"인내 전문가", name_en:"Great Fortitude", cat:"feature", class_id:"druid", feat_level:3, summary:"인내 내성 숙련도가 전문가로 증가."},
  {name_ko:"반사 전문가", name_en:"Lightning Reflexes", cat:"feature", class_id:"druid", feat_level:5, summary:"반사 내성 숙련도가 전문가로 증가."},
  {name_ko:"전문가 주문시전자", name_en:"Expert Spellcaster", cat:"feature", class_id:"druid", feat_level:7, summary:"마법 기법이 강해집니다. 주문 공격 수정치와 주문 DC 숙련도가 전문가로 증가."},
  {name_ko:"무기 전문가", name_en:"Druid Weapon Expertise", cat:"feature", class_id:"druid", feat_level:11, summary:"단순 무기, 비무장 공격 숙련도가 전문가로 증가."},
  {name_ko:"야생 의지력", name_en:"Wild Resolve", cat:"feature", class_id:"druid", feat_level:11, summary:"의지 내성 숙련도가 대가로. 의지 내성에서 성공 시 대성공."},
  {name_ko:"평갑 전문가", name_en:"Medium Armor Expertise", cat:"feature", class_id:"druid", feat_level:13, summary:"경갑, 평갑, 비무장 방어 숙련도가 전문가로 증가."},
  {name_ko:"무기 전문화", name_en:"Weapon Specialization", cat:"feature", class_id:"druid", feat_level:13, summary:"전문가인 무기와 비무장 공격으로 추가 피해 2(대가 3, 전설 4)."},
  {name_ko:"대가 주문시전자", name_en:"Master Spellcaster", cat:"feature", class_id:"druid", feat_level:15, summary:"주문 공격 수정치와 주문 DC 숙련도가 대가로 증가."},
  {name_ko:"전설 주문시전자", name_en:"Legendary Spellcaster", cat:"feature", class_id:"druid", feat_level:19, summary:"주문 공격 수정치와 주문 DC 숙련도가 전설로 증가."},
  {name_ko:"근원 대사제", name_en:"Primal Hierophant", cat:"feature", class_id:"druid", feat_level:19, summary:"근원 주문 목록에서 10랭크 주문 1개 + 10랭크 슬롯 1개."},
  {name_ko:"반격 타격", name_en:"Reactive Strike", cat:"feature", class_id:"fighter", feat_level:1, summary:"유발 조건: 도달 범위 내 생물이 조작 행동이나 이동 행동을 사용하거나, 원거리 공격을 하거나, 이동 중 칸을 떠납니다. 빈틈을 보이는 적을 신속히 공격합니다. 유발 생물에 근접 타격을 합니다. 치명타이고 유발이 조작 행동이면 행동을 방해합니다. 이 타격은 다중 공격 페널티에 포함되지 않으며, 다중 공격 페널티가 이 타격에 적용되지 않습니다."},
  {name_ko:"방패 막기", name_en:"Shield Block", cat:"feature", class_id:"fighter", feat_level:1, summary:"방패 막기(Shield Block) 일반 재주(262페이지)를 얻습니다."},
  {name_ko:"용기", name_en:"Bravery", cat:"feature", class_id:"fighter", feat_level:3, summary:"전투의 두려움을 이겨내는 훈련을 했습니다. 공포(fear) 효과에 대한 의지 내성에서 성공 시 대성공. 또한 공포 효과에 대한 의지 내성 숙련도가 전문가로 증가."},
  {name_ko:"파이터 무기 달인", name_en:"Fighter Weapon Mastery", cat:"feature", class_id:"fighter", feat_level:5, summary:"특정 무기 그룹에서 비할 데 없는 기술을 가지고 있습니다. 무기 그룹 하나를 선택합니다. 해당 그룹의 단순/군용 무기와 비무장 공격에 대한 숙련도가 대가로 증가. 해당 무기나 비무장 공격으로 치명타 시 치명 특성 효과를 적용합니다."},
  {name_ko:"전장 측량", name_en:"Battlefield Surveyor", cat:"feature", class_id:"fighter", feat_level:7, summary:"감지 숙련도가 대가로 증가."},
  {name_ko:"무기 전문화", name_en:"Weapon Specialization", cat:"feature", class_id:"fighter", feat_level:7, summary:"전문가인 무기/비무장 공격으로 추가 피해 2(대가 3, 전설 4)."},
  {name_ko:"전투 유연성", name_en:"Combat Flexibility", cat:"feature", class_id:"fighter", feat_level:9, summary:"일일 준비 시, 전제조건을 충족하는 8레벨 이하 파이터 재주 1개를 얻습니다. 다음 준비 시 다른 재주로 교체 가능."},
  {name_ko:"전투 단련", name_en:"Juggernaut", cat:"feature", class_id:"fighter", feat_level:9, summary:"의지 내성 숙련도가 전문가로 증가."},
  {name_ko:"갑옷 전문가", name_en:"Armor Expertise", cat:"feature", class_id:"fighter", feat_level:11, summary:"모든 갑옷과 비무장 방어 숙련도가 전문가로 증가."},
  {name_ko:"파이터 전문가", name_en:"Fighter Expertise", cat:"feature", class_id:"fighter", feat_level:11, summary:"파이터 클래스 DC 숙련도가 전문가로 증가."},
  {name_ko:"무기 전설", name_en:"Weapon Legend", cat:"feature", class_id:"fighter", feat_level:13, summary:"파이터 무기 달인으로 선택한 그룹의 단순/군용 무기와 비무장 공격 숙련도가 전설로 증가. 다른 단순/군용 무기와 비무장 공격은 대가로. 고급 무기 숙련도는 전문가로."},
  {name_ko:"번뜩이는 반사", name_en:"Evasion", cat:"feature", class_id:"fighter", feat_level:15, summary:"반사 내성에서 성공 시 대성공."},
  {name_ko:"상위 무기 전문화", name_en:"Greater Weapon Specialization", cat:"feature", class_id:"fighter", feat_level:15, summary:"무기 전문화의 추가 피해가 증가합니다. 전문가 4, 대가 6, 전설 8."},
  {name_ko:"향상된 유연성", name_en:"Improved Flexibility", cat:"feature", class_id:"fighter", feat_level:15, summary:"전투 유연성이 향상됩니다. 14레벨 이하 파이터 재주를 선택 가능. 2개의 재주를 선택하는 것으로도 변경 — 하나는 8레벨 이하, 다른 하나는 14레벨 이하."},
  {name_ko:"갑옷 달인", name_en:"Armor Mastery", cat:"feature", class_id:"fighter", feat_level:17, summary:"모든 갑옷과 비무장 방어 숙련도가 대가로 증가."},
  {name_ko:"다재다능한 전설", name_en:"Versatile Legend", cat:"feature", class_id:"fighter", feat_level:19, summary:"전투의 모든 측면을 익혔습니다. 파이터 클래스 DC가 대가로. 모든 단순/군용 무기와 비무장 공격이 전설로. 모든 고급 무기가 대가로 증가."},
  {name_ko:"사냥감 추적", name_en:"Hunt Prey", cat:"feature", class_id:"ranger", feat_level:1, summary:"볼 수 있거나 추적 중인 생물 1명을 사냥감으로 지정합니다. 사냥감을 탐색(Seek)하기 위한 감지 판정에 +2 상황 보너스, 추적(Track)을 위한 생존 판정에 +2 상황 보너스. 사냥감에 대한 두 번째 사거리 증분 내 원거리 공격 페널티도 무시합니다. 한 번에 사냥감 1명만 가능. 다음 일일 준비까지 지속."},
  {name_ko:"사냥꾼의 기질", name_en:"Hunter's Edge", cat:"feature", class_id:"ranger", feat_level:1, summary:"사냥감 추적 시 추가 혜택을 부여하는 기질을 선택합니다. 난타(Flurry): 사냥감에 대한 다중 공격 페널티가 완화됩니다. 두 번째 공격이 -5 대신 -3(민첩 무기 -2), 세 번째 이후가 -10 대신 -6(민첩 -4). 지략(Outwit): 사냥감의 공격에 대해 AC +1 상황 보너스, 사냥감에 대한 기만/위협/은신 및 지식 회상에 +2 상황 보너스. 정밀(Precision): 라운드에서 사냥감을 처음 명중할 때 추가 1d8 정밀 피해. 11레벨에서 2d8, 19레벨에서 3d8."},
  {name_ko:"의지 전문가", name_en:"Iron Will", cat:"feature", class_id:"ranger", feat_level:3, summary:"의지 내성 숙련도가 전문가로 증가."},
  {name_ko:"레인저 무기 전문가", name_en:"Ranger Weapon Expertise", cat:"feature", class_id:"ranger", feat_level:5, summary:"단순 무기, 군용 무기, 비무장 공격 숙련도가 전문가로 증가."},
  {name_ko:"흔적 없는 여정", name_en:"Trackless Journey", cat:"feature", class_id:"ranger", feat_level:5, summary:"험지를 이동할 때 흔적을 남기지 않으며, 추적하기 극히 어렵습니다."},
  {name_ko:"자연 반사", name_en:"Evasion", cat:"feature", class_id:"ranger", feat_level:7, summary:"반사 내성에서 성공 시 대성공."},
  {name_ko:"감지 달인", name_en:"Perception Master", cat:"feature", class_id:"ranger", feat_level:7, summary:"감지 숙련도가 대가로 증가."},
  {name_ko:"무기 전문화", name_en:"Weapon Specialization", cat:"feature", class_id:"ranger", feat_level:7, summary:"전문가인 무기와 비무장 공격으로 추가 피해 2(대가 3, 전설 4)."},
  {name_ko:"자연의 끝", name_en:"Nature", cat:"feature", class_id:"ranger", feat_level:9, summary:"험지에 있는 적은 당신에게 방심(off-guard)."},
  {name_ko:"레인저 전문가", name_en:"Ranger Expertise", cat:"feature", class_id:"ranger", feat_level:9, summary:"레인저 클래스 DC 숙련도가 전문가로 증가."},
  {name_ko:"관리인의 인내", name_en:"Warden", cat:"feature", class_id:"ranger", feat_level:11, summary:"인내 내성 숙련도가 대가로 증가. 인내 내성에서 성공 시 대성공."},
  {name_ko:"평갑 전문가", name_en:"Medium Armor Expertise", cat:"feature", class_id:"ranger", feat_level:11, summary:"경갑, 평갑, 비무장 방어 숙련도가 전문가로 증가."},
  {name_ko:"방해받지 않는 여정", name_en:"Unhindered Journey", cat:"feature", class_id:"ranger", feat_level:11, summary:"비마법 험지 이동 시 속도 페널티를 무시합니다. 선호 지형을 선택했다면 추가 혜택을 얻습니다."},
  {name_ko:"군용 무기 달인", name_en:"Weapon Mastery", cat:"feature", class_id:"ranger", feat_level:13, summary:"단순 무기, 군용 무기, 비무장 공격 숙련도가 대가로 증가."},
  {name_ko:"상위 자연 반사", name_en:"Greater Evasion", cat:"feature", class_id:"ranger", feat_level:15, summary:"반사 내성 숙련도가 대가로 증가. 반사 내성에서 대실패 시 실패. 피해를 주는 효과에 대한 반사 내성 실패 시 절반 피해."},
  {name_ko:"상위 무기 전문화", name_en:"Greater Weapon Specialization", cat:"feature", class_id:"ranger", feat_level:15, summary:"무기 전문화의 추가 피해가 증가합니다. 전문가 4, 대가 6, 전설 8."},
  {name_ko:"감지 전설", name_en:"Incredible Senses", cat:"feature", class_id:"ranger", feat_level:15, summary:"감지 숙련도가 전설로 증가."},
  {name_ko:"달인 사냥꾼", name_en:"Masterful Hunter", cat:"feature", class_id:"ranger", feat_level:17, summary:"사냥감 추적에 자유 행동이 아닌 1행동 대신 자유 행동으로 사냥감을 지정할 수 있습니다. 사냥꾼의 기질이 강화됩니다."},
  {name_ko:"평갑 달인", name_en:"Medium Armor Mastery", cat:"feature", class_id:"ranger", feat_level:19, summary:"경갑, 평갑, 비무장 방어 숙련도가 대가로 증가."},
  {name_ko:"신속 사냥감", name_en:"Swift Prey", cat:"feature", class_id:"ranger", feat_level:19, summary:"사냥감 추적을 자유 행동으로 사용할 수 있습니다."},
  {name_ko:"은밀 공격 1d6", name_en:"Sneak Attack 1d6", cat:"feature", class_id:"rogue", feat_level:1, summary:"방심(off-guard) 상태인 생물에 민첩/기교 근접 무기, 민첩/기교 비무장 공격, 원거리 무기/비무장 공격으로 타격 시 추가 1d6 정밀 피해. 투척 근접 무기는 민첩/기교여야 합니다. 5, 11, 17레벨에 피해 주사위가 1개씩 증가."},
  {name_ko:"기습", name_en:"Surprise Attack", cat:"feature", class_id:"rogue", feat_level:1, summary:"전투에 적보다 빨리 뛰어듭니다. 첫 라운드에 기만이나 은신으로 주도권을 굴렸으면, 아직 행동하지 않은 생물은 당신에게 방심."},
  {name_ko:"라켓", name_en:"Racket", cat:"feature", class_id:"rogue", feat_level:1, summary:"1레벨에 로그의 라켓을 선택합니다. 라켓은 로그로서의 활동 방식을 나타내며, 추가 기술과 핵심 속성 선택지를 부여합니다. 지략가, 건달, 사기꾼, 도둑 중 하나를 선택합니다."},
  {name_ko:"이점 부정", name_en:"Deny Advantage", cat:"feature", class_id:"rogue", feat_level:3, summary:"빈틈을 이용하는 자로서, 자신에게 그런 틈을 남기지 않습니다. 자신의 레벨 이하인 숨겨진/미탐지/측면 공격하는 생물이나 기습을 사용하는 생물에게 방심이 되지 않습니다(다른 이유로 방심은 여전히 가능). 그러나 그 생물은 아군의 측면 공격에 도움을 줄 수 있습니다."},
  {name_ko:"은밀 공격 2d6", name_en:"Sneak Attack 2d6", cat:"feature", class_id:"rogue", feat_level:5, summary:"은밀 공격 추가 정밀 피해가 2d6으로 증가합니다."},
  {name_ko:"무기 속임수", name_en:"Weapon Tricks", cat:"feature", class_id:"rogue", feat_level:5, summary:"단순 무기, 군용 무기, 비무장 공격 숙련도가 전문가로 증가."},
  {name_ko:"회피 반사", name_en:"Evasion", cat:"feature", class_id:"rogue", feat_level:7, summary:"반사 내성 숙련도가 대가로. 반사 내성에서 성공 시 대성공."},
  {name_ko:"경각 감각", name_en:"Vigilant Senses", cat:"feature", class_id:"rogue", feat_level:7, summary:"예리한 인식력과 세부 사항에 대한 주의력을 발달시켰습니다. 감지 숙련도가 대가로 증가."},
  {name_ko:"무기 전문화", name_en:"Weapon Specialization", cat:"feature", class_id:"rogue", feat_level:7, summary:"전문가인 무기와 비무장 공격으로 추가 피해 2(대가 3, 전설 4)."},
  {name_ko:"쇠약 타격", name_en:"Debilitating Strike", cat:"feature", class_id:"rogue", feat_level:9, summary:"유발 조건: 방심한 생물에 타격이 명중하고 피해를 줍니다. 다음 턴 종료까지 쇠약 효과 1개를 적용합니다: 이동 속도에 -10피트 상태 페널티 기력상실(enfeebled) 1"},
  {name_ko:"로그 회복력", name_en:"Rogue Resilience", cat:"feature", class_id:"rogue", feat_level:9, summary:"인내 내성 숙련도가 전문가로. 인내 내성에서 성공 시 대성공."},
  {name_ko:"은밀 공격 3d6", name_en:"Sneak Attack 3d6", cat:"feature", class_id:"rogue", feat_level:11, summary:"은밀 공격 추가 정밀 피해가 3d6으로 증가합니다."},
  {name_ko:"로그 전문가", name_en:"Rogue Expertise", cat:"feature", class_id:"rogue", feat_level:11, summary:"로그 클래스 DC 숙련도가 전문가로 증가."},
  {name_ko:"상위 로그 반사", name_en:"Greater Rogue Reflexes", cat:"feature", class_id:"rogue", feat_level:13, summary:"반사 내성 숙련도가 전설로. 반사 내성에서 대실패 시 실패. 피해를 주는 효과에 대한 반사 내성 실패 시 절반 피해."},
  {name_ko:"놀라운 감각", name_en:"Incredible Senses", cat:"feature", class_id:"rogue", feat_level:13, summary:"감지 숙련도가 전설로 증가."},
  {name_ko:"경갑 전문가", name_en:"Light Armor Expertise", cat:"feature", class_id:"rogue", feat_level:13, summary:"경갑이나 비무장 상태에서 피하는 법을 배웠습니다. 경갑과 비무장 방어 숙련도가 전문가로 증가."},
  {name_ko:"달인 속임수", name_en:"Master Tricks", cat:"feature", class_id:"rogue", feat_level:13, summary:"단순 무기, 군용 무기, 비무장 공격 숙련도가 대가로 증가."},
  {name_ko:"이중 쇠약", name_en:"Double Debilitation", cat:"feature", class_id:"rogue", feat_level:15, summary:"쇠약 타격 시 쇠약 효과 2개를 동시에 적용(하나를 제거하면 둘 다 제거)."},
  {name_ko:"민첩한 정신", name_en:"Slippery Mind", cat:"feature", class_id:"rogue", feat_level:17, summary:"의지 내성 숙련도가 대가로. 의지 내성에서 성공 시 대성공."},
  {name_ko:"은밀 공격 4d6", name_en:"Sneak Attack 4d6", cat:"feature", class_id:"rogue", feat_level:17, summary:"은밀 공격 추가 정밀 피해가 4d6으로 증가합니다."},
  {name_ko:"경갑 달인", name_en:"Light Armor Mastery", cat:"feature", class_id:"rogue", feat_level:19, summary:"경갑, 비무장 방어 숙련도가 대가로 증가."},
  {name_ko:"달인 타격", name_en:"Master Strike", cat:"feature", class_id:"rogue", feat_level:19, summary:"쇠약 타격 유발 시, 쇠약 효과 대신 대상에게 클래스 DC에 대해 인내 내성을 강제할 수 있습니다(무력화 효과). 대성공: 영향 없음. 성공: 쇠약 효과 적용. 실패: 쇠약 효과 + 느려짐(slowed) 2. 대실패: 마비(paralyzed) 1라운드 후 쇠약 + 느려짐 2."},
  {name_ko:"위치 주문시전", name_en:"Witch Spellcasting", cat:"feature", class_id:"witch", feat_level:1, summary:"사역마를 통로로 하여 후원자가 주문시전 능력을 부여합니다. 후원자의 전통으로 주문을 시전합니다. 매일 아침 사역마와 교감하여 주문을 준비합니다. 사역마가 알고 있는 주문에서 선택하여 주문 슬롯에 준비합니다."},
  {name_ko:"사역마", name_en:"Familiar", cat:"feature", class_id:"witch", feat_level:1, summary:"후원자가 보낸 신비로운 생물로, 마법을 가르치고 주문을 매개합니다. 일반 사역마보다 강력하며, 추가 사역마 능력 2개(후원자 고유 1개 + 매일 선택 1개)를 가집니다. 6, 12, 18레벨에 추가 능력 1개씩 더. 주문: 사역마가 캔트립 10개, 1랭크 주문 5개, 후원자의 첫 교훈 주문 1개를 알고 시작합니다. 레벨을 올릴 때마다 2개의 새 주문을 배웁니다. 사역마는 두루마리를 먹거나 다른 위치의 사역마에게서 주문을 배울 수도 있습니다. 불멸: 사역마가 죽으면 다음 일일 준비 시 후원자가 교체합니다. 같은 주문을 알고 있습니다."},
  {name_ko:"주술", name_en:"Hexes", cat:"feature", class_id:"witch", feat_level:1, summary:"후원자의 직접적 마법 개입인 주술은 집중 주문의 일종입니다. 턴당 주술 1개만 사용 가능(두 번째 시도는 자동 실패). 집중 풀 1점으로 시작하며, 10분간 사역마와 교감하여 1점 회복. 선택으로 후원자의 인형(patron's puppet) 또는 사역마 위상(phase familiar) 주술을 배웁니다."},
  {name_ko:"마법 인내", name_en:"Magical Fortitude", cat:"feature", class_id:"witch", feat_level:5, summary:"인내 내성 숙련도가 전문가로 증가."},
  {name_ko:"전문가 주문시전자", name_en:"Expert Spellcaster", cat:"feature", class_id:"witch", feat_level:7, summary:"마법 기법이 강해집니다. 주문 공격 수정치와 주문 DC 숙련도가 전문가로 증가."},
  {name_ko:"반사 전문가", name_en:"Lightning Reflexes", cat:"feature", class_id:"witch", feat_level:9, summary:"반사 내성 숙련도가 전문가로 증가."},
  {name_ko:"감지 전문가", name_en:"Alertness", cat:"feature", class_id:"witch", feat_level:11, summary:"감지 숙련도가 전문가로 증가."},
  {name_ko:"무기 전문가", name_en:"Witch Weapon Expertise", cat:"feature", class_id:"witch", feat_level:11, summary:"단순 무기, 비무장 공격 숙련도가 전문가로 증가."},
  {name_ko:"방어 법의", name_en:"Defensive Robes", cat:"feature", class_id:"witch", feat_level:13, summary:"비무장 방어 숙련도가 전문가로 증가."},
  {name_ko:"무기 전문화", name_en:"Weapon Specialization", cat:"feature", class_id:"witch", feat_level:13, summary:"전문가인 무기와 비무장 공격으로 추가 피해 2(대가 3, 전설 4)."},
  {name_ko:"대가 주문시전자", name_en:"Master Spellcaster", cat:"feature", class_id:"witch", feat_level:15, summary:"주문 공격 수정치와 주문 DC 숙련도가 대가로 증가."},
  {name_ko:"제자의 의지", name_en:"Apprentice", cat:"feature", class_id:"witch", feat_level:17, summary:"의지 내성 숙련도가 대가로. 의지 내성에서 성공 시 대성공."},
  {name_ko:"전설 주문시전자", name_en:"Legendary Spellcaster", cat:"feature", class_id:"witch", feat_level:19, summary:"주문 공격 수정치와 주문 DC 숙련도가 전설로 증가."},
  {name_ko:"후원자의 선물", name_en:"Patron", cat:"feature", class_id:"witch", feat_level:19, summary:"10랭크 주문 슬롯 1개를 얻습니다."},
  {name_ko:"비전 주문시전", name_en:"Arcane Spellcasting", cat:"feature", class_id:"wizard", feat_level:1, summary:"헌신적인 학습과 연습으로 비전 마법을 학술적 엄밀함으로 구성합니다. 비전(arcane) 전통의 주문시전자입니다. 매일 아침 주문서에서 주문을 준비하며, 비전 학파의 추가 캔트립 1개와 추가 주문도 준비합니다."},
  {name_ko:"비전 유대", name_en:"Arcane Bond", cat:"feature", class_id:"wizard", feat_level:1, summary:"마법적 힘의 일부를 결합 아이템에 저장합니다. 매일 준비 시 소유한 아이템 1개를 지정. 결합 아이템 소진(Drain Bonded Item) [자유 행동]을 얻어, 이미 시전한 준비 주문 1개를 슬롯 소비 없이 하루 1회 추가 시전 가능."},
  {name_ko:"비전 논제", name_en:"Arcane Thesis", cat:"feature", class_id:"wizard", feat_level:1, summary:"정식 위저드가 되는 과정에서 독자적 마법 연구의 논문을 작성했습니다. 논제에 따라 특별한 혜택을 얻습니다. 실험적 주문변형 Experimental Spellshaping — 주문변형의 마법 관행을 변수와 매개변수를 변경하여 더 효율적으로 실현할 수 있다는 논제입니다. 선택한 1레벨 주문변형 위저드 재주 1개를 얻습니다. 4레벨부터 일일 준비 시 레벨 절반 이하의 주문변형 위저드 재주를 추가로 얻을 수 있습니다. 향상된 사역마 동조 Improved Familiar Attunement — 위저드와 사역마의 마법적 유대를 미세 조정하면 더 큰 결과를 얻을 수 있다는 논제. 사역마(Familiar) 재주를 얻고, 사역마가 추가 능력 1개를 더 얻습니다(6, 12, 18레벨에 추가 1개씩). 비전 유대가 아이템 대신 사역마에 저장되어, 결합 아이템 소진(Drain Bonded Item) 대신 사역마 소진(Drain Familiar)을 얻습니다. 주문 혼합 Spell Blending — 주문 슬롯이 모든 주문시전에 힘을 공급하는 근본적 에너지의 약칭이라는 논제. 일일 준비 시, 같은 랭크의 주문 슬롯 2개를 최대 2랭크 높은 보너스 슬롯 1개로 교환할 수 있습니다. 주문 슬롯 1개를 캔트립 2개로 교환도 가능. 주문 대체 Spell Substitution — 준비된 주문은 다음 준비까지 변경할 수 없다는 사실을 거부합니다. 10분간 준비된 주문 슬롯 1개를 비우고 주문서에서 다른 주문을 준비할 수 있습니다. 지팡이 연결 Staff Nexus — 학습 초기부터 지팡이를 집중적으로 채택하면 주문시전자와 지팡이 사이에 공생적 유대를 만들 수 있다는 논제. 자작 지팡이로 시작(캔트립 1개 + 1랭크 주문 1개 포함). 일일 준비 시 주문 1개를 소비하여 해당 랭크만큼 지팡이에 충전. 8레벨에 주문 2개, 16레벨에 3개까지 소비 가능."},
  {name_ko:"비전 학파", name_en:"Arcane School", cat:"feature", class_id:"wizard", feat_level:1, summary:"1레벨에 비전 학파를 선택하며, 교과과정 주문과 학파 주문(집중 주문)을 얻습니다. 시전 가능한 각 주문 랭크에 학파 교과에서 추가 슬롯 1개씩을 얻고, 그 슬롯에는 교과 주문만 준비 가능합니다. 학파에는 소환(Ars Grammatica), 창조(Civic Wizardry), 변환(School of Mentalism), 점술(School of Protean Form), 환영(School of the Boundary) 등 8개 학파가 있으며, 통합 마법 이론(School of Unified Magical Theory)은 특정 학파에 속하지 않는 유연한 접근입니다."},
  {name_ko:"반사 전문가", name_en:"Lightning Reflexes", cat:"feature", class_id:"wizard", feat_level:5, summary:"반사 내성 숙련도가 전문가로 증가."},
  {name_ko:"전문가 주문시전자", name_en:"Expert Spellcaster", cat:"feature", class_id:"wizard", feat_level:7, summary:"마법 기법이 강해집니다. 주문 공격 수정치와 주문 DC 숙련도가 전문가로 증가."},
  {name_ko:"마법 인내", name_en:"Magical Fortitude", cat:"feature", class_id:"wizard", feat_level:9, summary:"인내 내성 숙련도가 전문가로 증가."},
  {name_ko:"감지 전문가", name_en:"Alertness", cat:"feature", class_id:"wizard", feat_level:11, summary:"감지 숙련도가 전문가로 증가."},
  {name_ko:"위저드 무기 전문가", name_en:"Wizard Weapon Expertise", cat:"feature", class_id:"wizard", feat_level:11, summary:"단순 무기, 비무장 공격 숙련도가 전문가로 증가."},
  {name_ko:"방어 법의", name_en:"Defensive Robes", cat:"feature", class_id:"wizard", feat_level:13, summary:"비무장 방어 숙련도가 전문가로 증가."},
  {name_ko:"무기 전문화", name_en:"Weapon Specialization", cat:"feature", class_id:"wizard", feat_level:13, summary:"전문가인 무기와 비무장 공격으로 추가 피해 2(대가 3, 전설 4)."},
  {name_ko:"대가 주문시전자", name_en:"Master Spellcaster", cat:"feature", class_id:"wizard", feat_level:15, summary:"주문 공격 수정치와 주문 DC 숙련도가 대가로 증가."},
  {name_ko:"놀라운 의지", name_en:"Resolve", cat:"feature", class_id:"wizard", feat_level:17, summary:"의지 내성 숙련도가 대가로. 의지 내성에서 성공 시 대성공."},
  {name_ko:"전설 주문시전자", name_en:"Legendary Spellcaster", cat:"feature", class_id:"wizard", feat_level:19, summary:"주문 공격 수정치와 주문 DC 숙련도가 전설로 증가."},
  {name_ko:"대위저드의 주문학", name_en:"Archwizard", cat:"feature", class_id:"wizard", feat_level:19, summary:"10랭크 주문 슬롯 1개를 얻습니다."},
];